   NODE_NAME:
       container_name: NODE_NAME 
       image: oceanprotocol/parity-ethereum:master
       user: root
       working_dir: /home/parity
       volumes:
       - ./deployment/chain/spec.json:/home/parity/spec.json:ro
       - ./deployment/chain/reserved_peers:/home/parity/reserved_peers:ro
       - ./deployment/NODE_NAME/password:/home/parity/password:ro
       - ./deployment/NODE_NAME/NODE_NAME.toml:/home/parity/NODE_NAME.toml:ro
       - ./deployment/NODE_NAME/${NETWORK_NAME}:/home/parity/data/keys/${NETWORK_NAME}
       - ./config/dev.json:/home/parity/data/keys/${NETWORK_NAME}/dev.json
       - ./deployment/NODE_NAME/key.priv:/home/parity/data/network/key
       - ./data/NODE_NAME:/home/parity/data
       command: --chain /home/parity/spec.json --config /home/parity/NODE_NAME.toml -d /home/parity/data
       networks: 
        eth-net:
            ipv4_address: '10.1.0.10IP'

