[parity]
chain = "/home/parity/chain.json"

[account]
password = ["/home/parity/password"]

[rpc]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["all"]

[ui]
disable = true

[network]
port = 30303
#bootnodes = ["enode://ssE2","enode://ssE3"]

[ipfs]
enable = false

[snapshots]
disable_periodic = true

[secretstore]
#self_secret = "accountx" 
disable = false
disable_http = false      # This node will expose a Secret Store HTTP API
http_interface = "all"  # The HTTP API is available locally only
http_port = 8010          # The Secret Store HTTP API is available at this port
acl_contract = "none"     # Insecure, will be changed later on
server_set_contract = "none"
#nodes = ["ssp1@10.1.0.21:8011","ssp2@10.1.0.22:8011","ssp3@10.1.0.23:8011"]
interface = "all"
port = 8011               # port used to communicated with other Secret Store n0des
path = "/parity/config/secret/db.ss1"

[misc]
logging = "own_tx=trace, engine, secretstore"