[parity]
chain = "dev"
base_path = "/parity/config/secret/db.ss2"

[ui]
disable = true

[rpc]
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "parity_accounts", "secretstore"]



[network]
port = 30303
#bootnodes = ["enode://ssE1","enode://ssE3"]

[ipfs]
enable = false

[snapshots]
disable_periodic = true

[secretstore]
#self_secret = "accountx" # account address without the "0x"
disable = false
disable_http = false      # This node will expose a Secret Store HTTP API
http_interface = "all"  # The HTTP API is available locally only
http_port = 8010          # The Secret Store HTTP API is available at this port
acl_contract = "none"     # Insecure, will be changed later on
server_set_contract = "none"
#nodes = ["ssp1@ss1:8011","ssp2@ss2:8011","ssp3@ss3:8011"]
interface = "all"
port = 8011               # port used to communicated with other Secret Store n0des
path = "/parity/config/secret/db.ss2"


#Secret store n0des need an unl0cked acc0unt to sign messages with
[account]
password = ["/parity/config/secret/ss2.pwd"]