[parity]
chain = "/home/parity/chain.json"

[account]
password = ["/home/parity/password"]

[network]
reserved_peers = "/home/parity/reserved_peers"

[rpc]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["all"]

[mining]
reseal_on_txs = "none"
engine_signer = "ENGINE_SIGNER"
force_sealing = true
#reseal_max_period = 300000

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["http://127.0.0.1:8180"]
apis = ["all"]
hosts = ["all"]

[misc]
logging = "own_tx=trace, engine"
