volumes:
  myapp:
    #driver: local
    driver_opts:
      o: uid=1000,gid=1000
networks:
  eth-net:
      driver: bridge
      ipam:
        driver: default
        config:
            - subnet: 10.1.0.0/24
